//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated from Assets/EditorData/CSV/NPCNameDB.csv
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

public static class NPCDataBase
{
    public static readonly Dictionary<int, (string name, int type)> NPCDB = new Dictionary<int, (string name, int type)>()
    {
       {1, ("한스", 0)},
       {2, ("한스", 0)},
       {3, ("지크", 0)},
       {4, ("헬렌", 1)},
       {5, ("마이크", 0)},
       {6, ("이장", 4)},
    };
}
