//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated from Assets/EditorData/CSV/MonsterDropTable.csv
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#if UNITY_EDITOR

using System.Collections.Generic;

public static class MonsterDropTableDataBase
{
    public static readonly Dictionary<int, List<DropTable>> monsterDropTableDB = new Dictionary<int, List<DropTable>>()
    {
        {
            10000, new List<DropTable>()
            {
                new DropTable(100001001, 1, 1, 20f),
                new DropTable(200100001, 1, 5, 60f),
                new DropTable(300000001, 1, 3, 50f),
                new DropTable(300000002, 1, 3, 50f),
                new DropTable(300000003, 1, 3, 50f),
                new DropTable(300000004, 1, 3, 50f),
            }
        },
        {
            10001, new List<DropTable>()
            {
                new DropTable(100001002, 1, 1, 30f),
                new DropTable(100001003, 1, 1, 10f),
                new DropTable(200100002, 1, 5, 40f),
                new DropTable(200100003, 2, 7, 10f),
                new DropTable(300000001, 1, 3, 80f),
                new DropTable(300000002, 1, 3, 80f),
                new DropTable(300000003, 1, 3, 80f),
                new DropTable(300000004, 1, 3, 80f),
                new DropTable(300000005, 1, 5, 40f),
            }
        },
        {
            10002, new List<DropTable>()
            {
                new DropTable(100001004, 1, 1, 50f),
                new DropTable(200100001, 20, 50, 100f),
                new DropTable(200100002, 20, 50, 100f),
                new DropTable(200100003, 20, 50, 100f),
                new DropTable(200100004, 3, 10, 30f),
                new DropTable(200100004, 20, 50, 100f),
                new DropTable(200200001, 20, 50, 100f),
                new DropTable(200200002, 20, 50, 100f),
                new DropTable(300000001, 10, 30, 100f),
                new DropTable(300000002, 10, 30, 100f),
                new DropTable(300000003, 10, 30, 100f),
                new DropTable(300000004, 10, 30, 100f),
                new DropTable(300000010, 1, 1, 100f),
            }
        },
    };
}
#endif
