//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated from Assets/EditorData/CSV/MonsterRewardDB.csv
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#if UNITY_EDITOR

using System.Collections.Generic;

public static class MonsterRewardDataBase
{
    public static readonly Dictionary<int, MonsterBaseReward> MonsterRewardDB = new Dictionary<int, MonsterBaseReward>()
    {
        { 10000, new MonsterBaseReward(3, 3, 6) },
        { 10001, new MonsterBaseReward(8, 10, 25) },
        { 10002, new MonsterBaseReward(100, 200, 500) },
        { 10003, new MonsterBaseReward(10, 10, 20) },
        { 10004, new MonsterBaseReward(15, 15, 30) },
    };
}
#endif
