//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated from Assets/EditorData/CSV/MonsterDB.csv
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#if UNITY_EDITOR

using System.Collections.Generic;

public static class MonsterDataBase
{
    public static readonly Dictionary<int, MonsterData> MonsterDB = new Dictionary<int, MonsterData>()
    {
        { 10000, new MonsterData(10000, 1, 30, 6f, 100f, 2f, 2f, 3f, 1f, 2f, 8f, 8f) },
        { 10001, new MonsterData(10001, 5, 50, 6f, 144f, 3f, 2f, 5f, 1.2f, 2f, 7f, 12f) },
        { 10002, new MonsterData(10002, 10, 500, 7f, 225f, 3f, 1f, 3f, 1.2f, 2f, 9f, 999999f) },
        { 10003, new MonsterData(10003, 4, 100, 7f, 225f, 3f, 1f, 2f, 1.3f, 2f, 9f, 5f) },
        { 10004, new MonsterData(10004, 5, 150, 7f, 225f, 3f, 1f, 1f, 1.2f, 2f, 7f, 5f) },
    };
}
#endif
