//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated from Assets/EditorData/CSV/ShopDB.csv
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#if UNITY_EDITOR

using System.Collections.Generic;

public static class ShopDataBase
{
    public static readonly Dictionary<int, List<ShopItemData>> ShopDB = new Dictionary<int, List<ShopItemData>>()
    {
        {
            4, new List<ShopItemData>()
            {
                new ShopItemData(200100001, 30),
                new ShopItemData(200100002, 30),
                new ShopItemData(200100003, 30),
                new ShopItemData(200100004, 30),
                new ShopItemData(200200001, 30),
                new ShopItemData(200200002, 30),
            }
        },
        {
            6, new List<ShopItemData>()
            {
                new ShopItemData(100001001, 500),
                new ShopItemData(100001002, 1000),
                new ShopItemData(100002001, 500),
                new ShopItemData(100003001, 500),
                new ShopItemData(100004001, 500),
                new ShopItemData(100005001, 500),
                new ShopItemData(100006001, 500),
            }
        },
    };
}
#endif
