//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated from Assets/EditorData/CSV/ShopDB.csv
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#if UNITY_EDITOR

using System.Collections.Generic;

public static class ShopDataBase
{
    public static readonly Dictionary<int, List<ShopItemData>> ShopDB = new Dictionary<int, List<ShopItemData>>()
    {
        {
            1, new List<ShopItemData>()
            {
                new ShopItemData(112302004, 500),
                new ShopItemData(110101002, 600),
                new ShopItemData(200100001, 100),
                new ShopItemData(300000002, 5),
            }
        },
        {
            2, new List<ShopItemData>()
            {
                new ShopItemData(121201003, 444),
                new ShopItemData(112302004, 111),
                new ShopItemData(200100002, 55),
                new ShopItemData(300000003, 3),
                new ShopItemData(300000004, 2),
            }
        },
    };
}
#endif
