//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated from Assets/EditorData/CSV/TalkDB.csv
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#if UNITY_EDITOR

using System.Collections.Generic;

public static class TalkDataBase
{
    public static readonly Dictionary<int, List<TalkData>> TalkDB = new Dictionary<int, List<TalkData>>()
    {
        {
            0, new List<TalkData>()
            {
                new TalkData(0, 0, 1, -1, "수락 할 퀘스트를 선택하세요."),
                new TalkData(0, 0, 3, -1, "이동하고 싶은 장소를 선택하세요."),
            }
        },
        {
            1, new List<TalkData>()
            {
                new TalkData(0, 0, 0, 1, "처음보는 사람이네?"),
                new TalkData(0, 0, 1, 1, "만나서 반가워!\n나는 한스야."),
                new TalkData(101, 0, 0, 1, "진짜 처음보는 사람이잖아?"),
                new TalkData(101, 0, 1, 1, "넌 어디서왔어?"),
                new TalkData(101, 0, 2, 1, "어쩌다 여기 오게된거야?"),
                new TalkData(101, 1, 0, 1, "기억을 잃었다고?"),
                new TalkData(101, 1, 1, 1, "이걸 어쩐담..."),
                new TalkData(101, 1, 2, 1, "나도 이런건 처음이라 당황스럽거든?\n잠깐만 기다려줄래?"),
                new TalkData(101, 2, 0, 1, "기억을 잃은건 내가 도와줄 수는 없지만, 이 주변에 대해서는 알려줄 수 있지."),
                new TalkData(101, 2, 1, 1, "아무튼 만나서 반갑다."),
                new TalkData(102, 0, 0, 1, "이 앞에 마을이 있어."),
                new TalkData(102, 0, 1, 1, "잠깐 우리 마을에서 머무는 건 어때?"),
                new TalkData(102, 0, 2, 1, "그런데, 마을 공터에 박쥐들이 나타나고 있거든. 같이 박쥐 좀 잡아주라."),
            }
        },
        {
            2, new List<TalkData>()
            {
                new TalkData(0, 0, 0, 2, "만나서 반가워!\n나는 한스야."),
                new TalkData(0, 0, 1, 2, "우리 마을에 온걸 환영해."),
                new TalkData(102, 2, 0, 2, "잘 잡는데? 박쥐사냥에 재능이 있어."),
                new TalkData(102, 2, 1, 2, "앞으로도 잘 부탁한다."),
                new TalkData(201, 0, 0, 2, "마을에 온 김에 마을사람들에게 인사나 하고 와"),
                new TalkData(201, 0, 1, 2, "선물 준비해둘테니까 인사 돌리고 다시 나한테 와"),
                new TalkData(201, 2, 0, 2, "모두에게 인사 돌리고 왔어?"),
                new TalkData(201, 2, 1, 2, "자, 여기 선물이야."),
                new TalkData(202, 0, 0, 2, "큰일이야.\n박쥐랑 버섯이 너무 많아지고있어."),
                new TalkData(202, 0, 1, 2, "마을사람들 도와서 너도 박쥐랑 버섯좀 잡아줘."),
                new TalkData(202, 2, 0, 2, "오, 많이 활약했더군."),
                new TalkData(202, 2, 1, 2, "보상을 준비했으니 받아가."),
                new TalkData(203, 0, 0, 2, "많이 강해졌네."),
                new TalkData(203, 0, 1, 2, "더 강해지는 방법이 있어.\n한번 들어볼래?"),
                new TalkData(203, 1, 0, 2, "일정 수준 이상 강해진 존재는 어떤 방법을 통해 더 강해질 수 있다고 해."),
                new TalkData(203, 1, 1, 2, "그리고 우린 그걸 전직이라고 부르지."),
                new TalkData(203, 1, 2, 2, "너라면 아마 전직이 가능할거야."),
                new TalkData(203, 2, 0, 2, "전직은 어떻게 하냐고?"),
                new TalkData(203, 2, 1, 2, "이장님을 찾아가봐."),
                new TalkData(203, 2, 2, 2, "그 분이 우리 마을에서 유일하게 전직을 해본 분이야."),
            }
        },
        {
            3, new List<TalkData>()
            {
                new TalkData(0, 0, 0, 3, "아 귀찮아."),
                new TalkData(0, 0, 1, 3, "이 돌 어때? 귀엽지않아?"),
                new TalkData(201, 1, 0, 3, "누구?"),
                new TalkData(201, 1, 1, 3, "그래, 잘부탁한다."),
                new TalkData(301, 0, 0, 3, "애완돌을 더 모아야겠어."),
                new TalkData(301, 0, 1, 3, "돌을 모아와줘."),
                new TalkData(301, 2, 0, 3, "많이 모아왔네."),
                new TalkData(301, 2, 1, 3, "고마워. 여기 답례."),
                new TalkData(302, 0, 0, 3, "더 많은 돌이 필요해."),
                new TalkData(302, 0, 1, 3, "또 모아줄 수 있어?"),
                new TalkData(302, 2, 0, 3, "이번에도 많이 모아왔네."),
                new TalkData(302, 2, 1, 3, "자, 여기 답례."),
            }
        },
        {
            4, new List<TalkData>()
            {
                new TalkData(0, 0, 0, 4, "안녕! 난 헬렌이야."),
                new TalkData(0, 0, 1, 4, "포션이 필요해?"),
                new TalkData(201, 1, 0, 4, "안녕! 난 헬렌이야.\n넌 누구니?"),
                new TalkData(201, 1, 1, 4, "잘 부탁해~"),
                new TalkData(401, 0, 0, 4, "나 좀 도와주라."),
                new TalkData(401, 0, 1, 4, "오늘 저녁으로 버섯요리를 하려고 하는데 버섯이 모자라."),
                new TalkData(401, 0, 2, 4, "버섯 좀 가져와 주라."),
                new TalkData(401, 2, 0, 4, "빨리 돌아왔네."),
                new TalkData(401, 2, 1, 4, "이정도면 많은 버섯 요리를 연구할 수 있겠어.\n고마워!"),
            }
        },
        {
            5, new List<TalkData>()
            {
                new TalkData(0, 0, 0, 5, "무슨 일 있어?"),
                new TalkData(0, 0, 1, 5, "없다면 다행이고."),
                new TalkData(201, 1, 0, 5, "처음보는 사람인데, 넌 누구지?"),
                new TalkData(201, 1, 1, 5, "무슨 일 생기면 불러.\n일 없는게 제일 좋지만."),
                new TalkData(501, 0, 0, 5, "윽... 습격이 있었어..."),
                new TalkData(501, 0, 1, 5, "급하게 막느라 포션을 안챙겨왔어..."),
                new TalkData(501, 0, 2, 5, "포션을 가져와줘..."),
                new TalkData(501, 2, 0, 5, "포션 가져왔어?"),
                new TalkData(501, 2, 1, 5, "이제 좀 낫군."),
                new TalkData(501, 2, 2, 5, "고마워. 이건 답례."),
            }
        },
        {
            6, new List<TalkData>()
            {
                new TalkData(0, 0, 0, 6, "반갑네. 내가 이 마을의 이장이네."),
                new TalkData(0, 0, 1, 6, "어떤 일로 찾아왔는가?"),
                new TalkData(201, 1, 0, 6, "한스에게 소식은 들었네."),
                new TalkData(201, 1, 1, 6, "잘 지내다가 가게나."),
                new TalkData(601, 0, 0, 6, "직업1로 전직을 하고 싶은가?"),
                new TalkData(601, 0, 1, 6, "그렇다면 잘 찾아왔네."),
                new TalkData(601, 1, 0, 6, "직업1은 이러이러한 직업일세."),
                new TalkData(601, 1, 1, 6, "나도 준비가 필요하니 조금 있다가 다시 찾아오게."),
                new TalkData(601, 2, 0, 6, "축하하네. 전직에 성공했군."),
                new TalkData(601, 2, 1, 6, "자네는 이제부터 직업1일세.\n더 강해지길 기원하네."),
                new TalkData(602, 0, 0, 6, "직업2로 전직을 하고 싶은가?"),
                new TalkData(602, 0, 1, 6, "그렇다면 잘 찾아왔네."),
                new TalkData(602, 1, 0, 6, "직업2는 이러이러한 직업일세."),
                new TalkData(602, 1, 1, 6, "나도 준비가 필요하니 조금 있다가 다시 찾아오게."),
                new TalkData(602, 2, 0, 6, "축하하네. 전직에 성공했군."),
                new TalkData(602, 2, 1, 6, "자네는 이제부터 직업2일세.\n더 강해지길 기원하네."),
                new TalkData(603, 0, 0, 6, "직업3으로 전직을 하고 싶은가?"),
                new TalkData(603, 0, 1, 6, "그렇다면 잘 찾아왔네."),
                new TalkData(603, 1, 0, 6, "직업3은 이러이러한 직업일세."),
                new TalkData(603, 1, 1, 6, "나도 준비가 필요하니 조금 있다가 다시 찾아오게."),
                new TalkData(603, 2, 0, 6, "축하하네. 전직에 성공했군."),
                new TalkData(603, 2, 1, 6, "자네는 이제부터 직업3일세.\n더 강해지길 기원하네."),
                new TalkData(604, 0, 0, 6, "직업4로 전직을 하고 싶은가?"),
                new TalkData(604, 0, 1, 6, "그렇다면 잘 찾아왔네."),
                new TalkData(604, 1, 0, 6, "직업4는 이러이러한 직업일세."),
                new TalkData(604, 1, 1, 6, "나도 준비가 필요하니 조금 있다가 다시 찾아오게."),
                new TalkData(604, 2, 0, 6, "축하하네. 전직에 성공했군."),
                new TalkData(604, 2, 1, 6, "자네는 이제부터 직업4일세.\n더 강해지길 기원하네."),
                new TalkData(605, 0, 0, 6, "직업5로 전직을 하고 싶은가?"),
                new TalkData(605, 0, 1, 6, "그렇다면 잘 찾아왔네."),
                new TalkData(605, 1, 0, 6, "직업5는 이러이러한 직업일세."),
                new TalkData(605, 1, 1, 6, "나도 준비가 필요하니 조금 있다가 다시 찾아오게."),
                new TalkData(605, 2, 0, 6, "축하하네. 전직에 성공했군."),
                new TalkData(605, 2, 1, 6, "자네는 이제부터 직업5일세.\n더 강해지길 기원하네."),
                new TalkData(606, 0, 0, 6, "큰일일세.\n언덕위에 스파크가 나타났어."),
                new TalkData(606, 0, 1, 6, "스파크는 우리 마을의 골칫거리일세.\n매 년, 마을사람들이 힘을 합쳐 저지했지만 사람들이 얼마 안남아서 더 이상 마을사람들의 힘만으로는 스파크를 몰아낼 수 없다네."),
                new TalkData(606, 0, 2, 6, "부디 자네가 우릴 도와주길 바라네."),
                new TalkData(606, 2, 0, 6, "스파크를 막아줘서 고맙네.\n자네는 우리 마을의 영웅이야."),
                new TalkData(606, 2, 1, 6, "언덕으로 가는 길의 반대편으로 가면 XXX마을이 있다네.\n자네의 목표가 그 곳에 있길 바라네."),
                new TalkData(606, 2, 2, 6, "우리 마을의 영웅의 앞길에 축복을."),
            }
        },
    };
}
#endif
