#if UNITY_EDITOR

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

public class MonsterRewardDBGenerator : ICsvToCodeGenerator
{
    public string csvPath => "Assets/EditorData/CSV/MonsterRewardDB.csv";
    public string outputScriptPath => "Assets/EditorData/DB/MonsterRewardDataBase.cs";

    Dictionary<int, MonsterBaseReward> monsterRewardDB = new Dictionary<int, MonsterBaseReward>();

    public void GenerateClassCode()
    {
        string dir = Path.GetDirectoryName(outputScriptPath);

        if (!Directory.Exists(dir))
        {
            Directory.CreateDirectory(dir);
        }

        using (StreamWriter writer = new StreamWriter(outputScriptPath, false, Encoding.UTF8))
        {
            writer.WriteLine("//------------------------------------------------------------------------------");
            writer.WriteLine("// <auto-generated>");
            writer.WriteLine("//     This code was auto-generated from Assets/EditorData/CSV/MonsterRewardDB.csv");
            writer.WriteLine("//     Changes to this file may cause incorrect behavior and will be lost if");
            writer.WriteLine("//     the code is regenerated.");
            writer.WriteLine("// </auto-generated>");
            writer.WriteLine("//------------------------------------------------------------------------------");
            writer.WriteLine();
            writer.WriteLine("#if UNITY_EDITOR");
            writer.WriteLine();
            writer.WriteLine("using System.Collections.Generic;");
            writer.WriteLine();
            writer.WriteLine("public static class MonsterRewardDataBase");
            writer.WriteLine("{");
            writer.WriteLine("    public static readonly Dictionary<int, MonsterBaseReward> MonsterRewardDB = new Dictionary<int, MonsterBaseReward>()");
            writer.WriteLine("    {");

            if (monsterRewardDB == null || monsterRewardDB.Count == 0)
            {
                writer.WriteLine("    };");
                writer.WriteLine("}");
                writer.WriteLine("#endif");
                return;
            }

            foreach (var kvp in monsterRewardDB)
            {
                writer.WriteLine($"        {{ {kvp.Key}, new MonsterBaseReward({kvp.Value.exp}, {kvp.Value.minGold}, {kvp.Value.maxGold}) }},");
            }

            writer.WriteLine("    };");
            writer.WriteLine("}");
            writer.WriteLine("#endif");
        }
    }

    public void ReadCSV()
    {
        TextAsset csv = AssetDatabase.LoadAssetAtPath<TextAsset>(csvPath);

        if (csv == null)
        {
            DevelopUtility.Log("csv 파일을 찾을 수 없음");
            return;
        }

        var lines = csv.text.Split(new[] { "\r\n", "\n\r", "\n", "\r" }, StringSplitOptions.None);

        for (int i = 1; i < lines.Length; i++)
        {
            var values = lines[i].Split(',');

            if (values.Length == 0 || string.IsNullOrEmpty(values[0])) continue;

            int id = CSVReader.GetIntData(values[0]);

            MonsterBaseReward rewardData = new MonsterBaseReward(CSVReader.GetIntData(values[1]), CSVReader.GetIntData(values[2]), CSVReader.GetIntData(values[3]));

            monsterRewardDB[id] = rewardData;
        }

        GenerateClassCode();

        AssetDatabase.Refresh();
    }
}
#endif