using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

#if UNITY_EDITOR
public class MonsterDataBaseGenerator : ICsvToCodeGenerator
{
    public string csvPath => "Assets/EditorData/CSV/MonsterDB.csv";
    public string outputScriptPath => "Assets/EditorData/DB/MonsterDataBase.cs";

    Dictionary<int, MonsterData> monsterDB = new Dictionary<int, MonsterData>();

    public void GenerateClassCode()
    {
        string dir = Path.GetDirectoryName(outputScriptPath);

        if (!Directory.Exists(dir))
        {
            Directory.CreateDirectory(dir);
        }

        using (StreamWriter writer = new StreamWriter(outputScriptPath, false, Encoding.UTF8))
        {
            writer.WriteLine("//------------------------------------------------------------------------------");
            writer.WriteLine("// <auto-generated>");
            writer.WriteLine("//     This code was auto-generated from Assets/EditorData/CSV/MonsterDB.csv");
            writer.WriteLine("//     Changes to this file may cause incorrect behavior and will be lost if");
            writer.WriteLine("//     the code is regenerated.");
            writer.WriteLine("// </auto-generated>");
            writer.WriteLine("//------------------------------------------------------------------------------");
            writer.WriteLine();
            writer.WriteLine("#if UNITY_EDITOR");
            writer.WriteLine();
            writer.WriteLine("using System.Collections.Generic;");
            writer.WriteLine();
            writer.WriteLine("public static class MonsterDataBase");
            writer.WriteLine("{");
            writer.WriteLine("    public static readonly Dictionary<int, MonsterData> MonsterDB = new Dictionary<int, MonsterData>()");
            writer.WriteLine("    {");

            if (monsterDB == null || monsterDB.Count == 0)
            {
                writer.WriteLine("    };");
                writer.WriteLine("}");
                writer.WriteLine("#endif");
                return;
            }

            foreach (var kvp in monsterDB)
            {
                writer.WriteLine($"        {{ {kvp.Key}, new MonsterData({kvp.Value.id}, {kvp.Value.level}, {kvp.Value.maxHp}, {kvp.Value.trackingRange}f, {kvp.Value.limitTrackingRange}f, {kvp.Value.limitTrackingHeight}f, {kvp.Value.minIdleTime}f, {kvp.Value.maxIdleTime}f, {kvp.Value.idleMoveSpeed}f, {kvp.Value.trackingMoveSpeed}f, {kvp.Value.returnMoveSpeed}f, {kvp.Value.respawnTime}f) }},");
            }

            writer.WriteLine("    };");
            writer.WriteLine("}");
            writer.WriteLine("#endif");
        }
    }

    public void ReadCSV()
    {
        TextAsset csv = AssetDatabase.LoadAssetAtPath<TextAsset>(csvPath);

        if (csv == null)
        {
            DevelopUtility.Log("csv 파일을 찾을 수 없음");
            return;
        }

        var lines = csv.text.Split(new[] { "\r\n", "\n\r", "\n", "\r" }, StringSplitOptions.None);

        for (int i = 1; i < lines.Length; i++)
        {
            var values = lines[i].Split(',');

            if (values.Length == 0 || string.IsNullOrEmpty(values[0])) continue;

            int id = CSVReader.GetIntData(values[0]);

            MonsterData monsterData = new MonsterData(CSVReader.GetIntData(values[0]), CSVReader.GetIntData(values[1]), CSVReader.GetIntData(values[2]), CSVReader.GetFloatData(values[3]), CSVReader.GetFloatData(values[4]), CSVReader.GetFloatData(values[5]), CSVReader.GetFloatData(values[6]), CSVReader.GetFloatData(values[7]), CSVReader.GetFloatData(values[8]), CSVReader.GetFloatData(values[9]), CSVReader.GetFloatData(values[10]), CSVReader.GetFloatData(values[11]));

            monsterDB[id] = monsterData;
        }

        GenerateClassCode();

        AssetDatabase.Refresh();
    }
}
#endif