#if UNITY_EDITOR

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;


public class MonsterDropTableDataBaseGenerator : ICsvToCodeGenerator
{
    public string csvPath => "Assets/EditorData/CSV/MonsterDropTable.csv";
    public string outputScriptPath => "Assets/EditorData/DB/MonsterDropTableDataBase.cs";

    Dictionary<int, List<DropTable>> monsterDropTableDB = new Dictionary<int, List<DropTable>>();
    public void GenerateClassCode()
    {
        string dir = Path.GetDirectoryName(outputScriptPath);

        if (!Directory.Exists(dir))
        {
            Directory.CreateDirectory(dir);
        }

        using (StreamWriter writer = new StreamWriter(outputScriptPath, false, Encoding.UTF8))
        {
            writer.WriteLine("//------------------------------------------------------------------------------");
            writer.WriteLine("// <auto-generated>");
            writer.WriteLine("//     This code was auto-generated from Assets/EditorData/CSV/MonsterDropTable.csv");
            writer.WriteLine("//     Changes to this file may cause incorrect behavior and will be lost if");
            writer.WriteLine("//     the code is regenerated.");
            writer.WriteLine("// </auto-generated>");
            writer.WriteLine("//------------------------------------------------------------------------------");
            writer.WriteLine();
            writer.WriteLine("#if UNITY_EDITOR");
            writer.WriteLine();
            writer.WriteLine("using System.Collections.Generic;");
            writer.WriteLine();
            writer.WriteLine("public static class MonsterDropTableDataBase");
            writer.WriteLine("{");
            writer.WriteLine("    public static readonly Dictionary<int, List<DropTable>> monsterDropTableDB = new Dictionary<int, List<DropTable>>()");
            writer.WriteLine("    {");

            if (monsterDropTableDB == null || monsterDropTableDB.Count == 0)
            {
                writer.WriteLine("    };");
                writer.WriteLine("}");
                writer.WriteLine("#endif");
                return;
            }

            foreach (var kvp in monsterDropTableDB)
            {
                writer.WriteLine("        {");
                writer.WriteLine($"            {kvp.Key}, new List<DropTable>()");
                writer.WriteLine("            {");
                foreach (var dropTable in kvp.Value)
                {
                    writer.WriteLine($"                new DropTable({dropTable.itemNumber}, {dropTable.minAmount}, {dropTable.maxAmount}, {dropTable.probability}f),");
                }
                writer.WriteLine("            }");
                writer.WriteLine("        },");
            }

            writer.WriteLine("    };");
            writer.WriteLine("}");
            writer.WriteLine("#endif");
        }
    }

    public void ReadCSV()
    {
        TextAsset csv = AssetDatabase.LoadAssetAtPath<TextAsset>(csvPath);

        if (csv == null)
        {
            DevelopUtility.Log("csv 파일을 찾을 수 없음");
            return;
        }

        var lines = csv.text.Split(new[] { "\r\n", "\n\r", "\n", "\r" }, StringSplitOptions.None);

        for (int i = 1; i < lines.Length; i++)
        {
            var values = lines[i].Split(',');

            if (values.Length == 0 || string.IsNullOrEmpty(values[0])) continue;

            int id = CSVReader.GetIntData(values[0]);

            var dropTable = new DropTable(
                CSVReader.GetIntData(values[1]),
                CSVReader.GetIntData(values[2]),
                CSVReader.GetIntData(values[3]),
                CSVReader.GetFloatData(values[4])
            );

            if (!monsterDropTableDB.ContainsKey(id))
            {
                monsterDropTableDB[id] = new List<DropTable>();
            }
            monsterDropTableDB[id].Add(dropTable);
        }

        GenerateClassCode();

        AssetDatabase.Refresh();
    }
}

#endif