using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

public class NPCNameDataBaseGenerator : ICsvToCodeGenerator
{
    public string csvPath => "Assets/EditorData/CSV/NPCNameDB.csv";
    public string outputScriptPath => "Assets/Scripts/DB/NPCDataBase.cs";
    Dictionary<int, (string name, int type)> NPCDB = new Dictionary<int, (string name, int type)>();

    public void GenerateClassCode()
    {
        string dir = Path.GetDirectoryName(outputScriptPath);

        if (!Directory.Exists(dir))
        {
            Directory.CreateDirectory(dir);
        }

        using (StreamWriter writer = new StreamWriter(outputScriptPath, false, Encoding.UTF8))
        {
            writer.WriteLine("//------------------------------------------------------------------------------");
            writer.WriteLine("// <auto-generated>");
            writer.WriteLine("//     This code was auto-generated from Assets/EditorData/CSV/NPCNameDB.csv");
            writer.WriteLine("//     Changes to this file may cause incorrect behavior and will be lost if");
            writer.WriteLine("//     the code is regenerated.");
            writer.WriteLine("// </auto-generated>");
            writer.WriteLine("//------------------------------------------------------------------------------");
            writer.WriteLine();
            writer.WriteLine("using System.Collections.Generic;");
            writer.WriteLine();
            writer.WriteLine("public static class NPCDataBase");
            writer.WriteLine("{");
            writer.WriteLine("    public static readonly Dictionary<int, (string name, int type)> NPCDB = new Dictionary<int, (string name, int type)>()");
            writer.WriteLine("    {");

            if (NPCDB == null || NPCDB.Count == 0)
            {
                writer.WriteLine("    };");
                writer.WriteLine("}");
                writer.WriteLine("#endif");
                return;
            }

            foreach (var kvp in NPCDB)
            {
                writer.WriteLine($"       {{{kvp.Key}, (\"{kvp.Value.name}\", {kvp.Value.type})}},");
            }
            writer.WriteLine("    };");
            writer.WriteLine("}");
        }
    }
    public void ReadCSV()
    {
        TextAsset csv = AssetDatabase.LoadAssetAtPath<TextAsset>(csvPath);

        if (csv == null)
        {
            DevelopUtility.Log("csv 파일을 찾을 수 없음");
            return;
        }

        var lines = csv.text.Split(new[] { "\r\n", "\n\r", "\n", "\r" }, StringSplitOptions.None);

        for (int i = 1; i < lines.Length; i++)
        {
            var values = lines[i].Split(',');

            if (values.Length == 0 || string.IsNullOrEmpty(values[0])) continue;

            int id = CSVReader.GetIntData(values[0]);
            string name = CSVReader.GetStringData(values[1]);
            int type = CSVReader.GetIntData(values[2]);
            NPCDB[id] = (name, type);
        }

        GenerateClassCode();

        AssetDatabase.Refresh();
    }
}
